# routeros_interfaces (Data Source)


## Example Usage
```terraform
data "routeros_interfaces" "interfaces" {}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Optional

- `___id___` (Number) <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
- `___path___` (String) <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
- `___skip___` (String) <em>A set of transformations for field names. This is an internal service field, setting a value is not required.</em>
- `filter` (Map of String) Additional request filtering options.

### Read-Only

- `id` (String) The ID of this resource.
- `interfaces` (List of Object) (see [below for nested schema](#nestedatt--interfaces))

<a id="nestedatt--interfaces"></a>
### Nested Schema for `interfaces`

Read-Only:

- `actual_mtu` (Number)
- `comment` (String)
- `default_name` (String)
- `disabled` (Boolean)
- `dynamic` (Boolean)
- `id` (String)
- `l2mtu` (Number)
- `last_link_down_time` (String)
- `last_link_up_time` (String)
- `mac_address` (String)
- `max_l2mtu` (Number)
- `mtu` (String)
- `name` (String)
- `running` (Boolean)
- `slave` (Boolean)
- `type` (String)


