# routeros_ip_arp (Data Source)


## Example Usage
```terraform
data "routeros_ip_arp" "data" {}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Optional

- `___id___` (Number) <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
- `___path___` (String) <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
- `filter` (Map of String) Additional request filtering options.

### Read-Only

- `data` (List of Object) (see [below for nested schema](#nestedatt--data))
- `id` (String) The ID of this resource.

<a id="nestedatt--data"></a>
### Nested Schema for `data`

Read-Only:

- `address` (String)
- `complete` (Boolean)
- `dhcp` (Boolean)
- `disabled` (Boolean)
- `dynamic` (Boolean)
- `id` (String)
- `interface` (String)
- `invalid` (Boolean)
- `mac_address` (String)
- `published` (Boolean)


