// Code generated by "tools/drift/main.go"; DO NOT EDIT.
package routeros

func init() {
    driftAttributeSlice.Add("7.1", "/ip/dhcp-server", "src_address", "server-address")
    driftAttributeSlice.Add("7.17", "/interface/wireguard/peers", "is_responder", "responder")
    driftAttributeSlice.Add("7.18", "/container", "tag", "repo")
    driftAttributeSlice.SortDesc()
}
