// Code generated by "tools/drift/main.go"; DO NOT EDIT.
package routeros

func init() {
    driftAttributeSlice.Add("7.1", "/ip/dhcp-server", "src_address", "server-address")
    driftAttributeSlice.Add("7.1", "/routing/ospf/area", "nssa_translate", "nssa-translator")
    driftAttributeSlice.Add("7.17", "/interface/wireguard/peers", "is_responder", "responder")
    driftAttributeSlice.Add("7.18", "/container", "tag", "repo")
    driftAttributeSlice.Add("7.19", "/routing/bgp/connection", "address_families", "afi")
    driftAttributeSlice.Add("7.19", "/routing/bgp/template", "address_families", "afi")
    driftAttributeSlice.Add("7.20", "/container", "envlist", "envlists")
    driftAttributeSlice.Add("7.20", "/container/config", "ram_high", "memory-high")
    driftAttributeSlice.Add("7.20", "/container/envs", "name", "list")
    driftAttributeSlice.Add("7.20", "/interface/vxlan", "vrf", "vtep-vrf")
    driftAttributeSlice.SortDesc()
}
