// Code generated by "tools/drift/main.go"; DO NOT EDIT.
package routeros

func init() {
    driftAttributeSlice.Add("7.17", "/interface/wireguard/peers", "is_responder", "responder")
    driftAttributeSlice.SortDesc()
}
