# routeros_dhcp_client_option (Resource)




<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `code` (Number) The dhcp-client option code.
- `name` (String) The name that will be used in dhcp-client.

### Optional

- `___id___` (Number) <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
- `___path___` (String) <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
- `raw_value` (String) raw_value is computed from value.
- `value` (String) The dhcp-client option

### Read-Only

- `id` (String) The ID of this resource.


