# routeros_interface_ethernet_switch_port_isolation (Resource)


## Example Usage
```terraform
resource "routeros_interface_ethernet_switch_port_isolation" "test" {
  name                = "ether1"
  forwarding_override = "ether1"
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `name` (String) Port name.

### Optional

- `___id___` (Number) <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
- `___path___` (String) <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
- `___skip___` (String) <em>A set of transformations for field names. This is an internal service field, setting a value is not required.</em>
- `___unset___` (String) <em>A set of fields that require setting/unsetting. This is an internal service field, setting a value is not required.</em>
- `forwarding_override` (String) Forces ingress traffic to be forwarded to a specific interface. Multiple interfaces can be specified by separating them with a comma.

### Read-Only

- `id` (String) The ID of this resource.
- `invalid` (Boolean)
- `switch` (String) Name of the switch.

## Import
Import is supported using the following syntax:
```shell
#The ID can be found via API or the terminal
#The command for the terminal is -> :put [/interface/ethernet/switch/port-isolation get [print show-ids]]
terraform import routeros_interface_ethernet_switch_port_isolation.test *1
```
