# routeros_ip_firewall_addr_list (Resource)


## Example Usage
```terraform
resource "routeros_ip_firewall_addr_list" "example_list" {
  address = "1.1.1.1"
  list    = "Example List"
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `address` (String) A single IP address or range of IPs to add to address list or DNS name. You can input for example, '192.168.0.0-192.168.1.255' and it will auto modify the typed entry to 192.168.0.0/23 on saving.
- `list` (String) Name for the address list of the added IP address.

### Optional

- `___id___` (Number) <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
- `___path___` (String) <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
- `comment` (String)
- `disabled` (Boolean)
- `timeout` (String) Time after address will be removed from address list. If timeout is not specified,
the address will be stored into the address list permanently.  
	> Please plan your work logic based on the fact that after the timeout    
	> the resource has been destroyed outside of Terraform.

### Read-Only

- `creation_time` (String) Rule creation time
- `dynamic` (Boolean) Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
- `id` (String) The ID of this resource.

## Import
Import is supported using the following syntax:
```shell
#The ID can be found via API or the terminal
#The command for the terminal is -> :put [/ip/firewall/address-list get [print show-ids]]
terraform import routeros_ip_firewall_addr_list.example_list "*0"
```
