# routeros_system_routerboard_button_reset (Resource)




<!-- schema generated by tfplugindocs -->
## Schema

### Optional

- `___id___` (Number) <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
- `___path___` (String) <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
- `enabled` (Boolean) An option to enable the operation of the button.
- `hold_time` (String) An option to define the period within which the button should be pressed.
- `on_event` (String) An option to set the script that will be run upon pressing the button.

### Read-Only

- `id` (String) The ID of this resource.


