# routeros_system_ntp_server (Resource)


## Example Usage
```terraform
resource "routeros_system_ntp_server" "test" {
  enabled             = true
  broadcast           = true
  multicast           = true
  manycast            = true
  use_local_clock     = true
  local_clock_stratum = 3
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Optional

- `___id___` (Number) <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
- `___path___` (String) <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
- `auth_key` (String) NTP symmetric key, used for authentication between the NTP client and server. Key Identifier (Key ID) - an integer identifying the cryptographic key used to generate the message-authentication code.
- `broadcast` (Boolean) Enable certain NTP server mode, for this mode to work you have to set up broadcast-addresses field.
- `broadcast_addresses` (String) Set broadcast address to use for NTP server broadcast mode.
- `enabled` (Boolean) Enable NTP server.
- `local_clock_stratum` (Number) Manually set stratum if ```use_local_clock = true```.
- `manycast` (Boolean) Enable certain NTP server mode.
- `multicast` (Boolean) Enable certain NTP server mode.
- `use_local_clock` (Boolean) The server will supply its local system time as valid if others are not available.
- `vrf` (String) The VRF table this resource operates on.

### Read-Only

- `id` (String) The ID of this resource.

## Import
Import is supported using the following syntax:
```shell
terraform import routeros_system_ntp_server.test .
```
