# routeros_user_manager_settings (Resource)


## Example Usage
```terraform
resource "routeros_user_manager_settings" "settings" {
  enabled = true
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Optional

- `___id___` (Number) <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
- `___path___` (String) <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
- `accounting_port` (Number) Port to listen for RADIUS accounting requests.
- `authentication_port` (Number) Port to listen for RADIUS authentication requests.
- `certificate` (String) Certificate for use in EAP TLS-type authentication methods.
- `enabled` (Boolean) An option whether the User Manager functionality is enabled.
- `require_message_auth` (String) An option whether to require `Message-Authenticator` in received Access-Accept/Challenge/Reject messages.
- `use_profiles` (Boolean) An option whether to use Profiles and Limitations. When set to `false`, only User configuration is required to run User Manager.

### Read-Only

- `id` (String) The ID of this resource.

## Import
Import is supported using the following syntax:
```shell
terraform import routeros_user_manager_settings.settings .
```
